### PR TITLE
Adds a link only if there is one

### PR DESCRIPTION
**Pull request by rrees**
I wanted to be able to click on a link if someone has supplied it, I found cut and pasting a pain.

The inline if statement seemed like the cleanest thing to do given the way the post is modelled.

### CODE REVIEW

**Comment by 200WordRPG** [comment]
This is a good idea, however many many entries do NOT have properly formatting HTML links. Their link might say "google.com" or "@david". I figured a bunch of broken links would be worse than simply letting people see whatever was entered.

**Comment by rrees** [comment]
I could make the check more sophisticated to check for valid links but really I feel this is 80:20. When I see something that looks like a link that doesn't work it's confusing but if I see `@david` as a link I wouldn't be shocked to discover that it doesn't work.

**Comment by 200WordRPG** [comment]
I wonder if there's a way to use the web browsers super search features.

E.g. if I type in "schirduans.com" it's not a valid http address, but the browser fills in the blanks and makes it work. Likewise if I type "@tomjones" it automatically google searches the result.

Any html magic that can force that browser auto behavior?

**Comment by 200WordRPG** [comment]
let's implement your fix, see if it works with the browser feature. I'm merging it in.

**Comment by 200WordRPG** [comment]
So now we have a weird problem where non-http links append to the site. E.g. google.com links to:

https://200wordrpg.github.io/2017/rpg/2017/04/19/google.com

Know how we can keep it from appending?

**Comment by rrees** [comment]
@200WordRPG Do you build the site before deploying it or does Github do it automatically?

**Comment by 200WordRPG** [comment]
Github does it as part of their "Pages" program. After every commit it runs the jekyll build command and reports any errors to my email. Hence why I have so many dumb commits; I'm testing the jekyll build process.

**Comment by rrees** [comment]
Okay I'll try and do this in a smart way client-side

**Pull request merged**
